const formats: string[] = [
    'yyyy-MM-dd',
    'yyyy-MM-dd hh:mm a',
    'yyyy-MM-dd HH:mm',
    'yyyy-MM-dd HH:mm ZZZ',
    'yyyy-MM-dd HH:mm ZZZ',
    'yyyy-MM-dd HH:mm ZZZ',
    'yyyy-MM-dd\'T\'HH:mm',
    'yyyy-MM-dd\'T\'HH:mm',
    'yyyy-MM-dd\'T\'HH:mm ZZZ',
    'MMMM DD, yyyy HH:mm',
    'MMMM d\'nd\', yyyy',
    'MMMM d\'nd\', yyyy',
    'MMMM d\'nd\', yyyy hh a',
    'MMMM d\'nd\', yyyy hh a ZZZ',
    'MMMM d\'nd\', yyyy ZZZ',
    'MMMM d\'nd\', yyyy hh:mm',
    'MMMM d\'nd\', yyyy hh:mm a',
    'MMMM d\'nd\', yyyy hh:mm a ZZZ',
    'MMMM d\'th\', yyyy',
    'MMMM d\'th\', yyyy hh a',
    'MMMM d\'th\', yyyy hh a ZZZ',
    'MMMM d\'th\', yyyy ZZZ',
    'MMMM d\'th\', yyyy hh:mm',
    'MMMM d\'th\', yyyy hh:mm a',
    'MMMM d\'th\', yyyy hh:mm a ZZZ',
  ];

  export default formats;