const timezones = {
  "ACDT": ["Australia/Adelaide"],
  "ACST": ["Australia/Darwin"],
  "ACT": ["America/Bogota", "Australia/Brisbane", "Australia/Sydney"],
  "ADT": ["America/Halifax"],
  "AEDT": ["Australia/Sydney"],
  "AEST": ["Australia/Brisbane"],
  "AFT": ["Asia/Kabul"],
  "AKDT": ["America/Anchorage"],
  "AKST": ["America/Anchorage"],
  "ALMT": ["Asia/Almaty"],
  "AMST": ["America/Cuiaba", "America/Manaus", "America/Santiago", "Asia/Yerevan"],
  "AMT": ["America/Cuiaba", "America/Manaus", "America/Santiago", "Asia/Yerevan"],
  "ANAT": ["Asia/Anadyr"],
  "AQTT": ["Asia/Aqtau", "Asia/Aqtobe"],
  "ART": ["America/Argentina/Buenos_Aires"],
  "AST": ["America/Blanc-Sablon", "America/Halifax", "Asia/Baghdad", "Atlantic/Stanley"],
  "AWST": ["Asia/Shanghai"],
  "AZOST": ["Atlantic/Azores"],
  "AZOT": ["Atlantic/Azores"],
  "AZT": ["Asia/Baku"],
  "AoE": ["Etc/GMT+12"],
  "BNT": ["Asia/Brunei"],
  "BOT": ["America/La_Paz"],
  "BRST": ["America/Sao_Paulo"],
  "BRT": ["America/Sao_Paulo"],
  "BST": ["America/Adak", "America/Nome", "Asia/Dhaka", "Europe/London"],
  "BTT": ["Asia/Thimphu"],
  "CAT": ["Africa/Maputo"],
  "CCT": ["Indian/Cocos"],
  "CDT": ["America/Chicago", "America/Regina", "Asia/Ho_Chi_Minh"],
  "CEST": ["Europe/Paris"],
  "CET": ["Europe/Paris"],
  "CHADT": ["Pacific/Chatham"],
  "CHAST": ["Pacific/Chatham"],
  "CHOT": ["Asia/Choibalsan"],
  "CHOST": ["Asia/Choibalsan"],
  "CHST": ["Pacific/Guam"],
  "CHUT": ["Pacific/Chuuk"],
  "CIST": ["Pacific/Enderbury"],
  "CIT": ["Asia/Makassar"],
  "CKT": ["Pacific/Rarotonga"],
  "CLST": ["America/Santiago"],
  "CLT": ["America/Santiago"],
  "COST": ["America/Bogota"],
  "COT": ["America/Bogota"],
  "CST": ["America/Belize", "America/Chicago", "Asia/Harbin", "Asia/Shanghai", "America/Regina", "Asia/Ho_Chi_Minh"],
  "CT": ["Asia/Harbin", "Asia/Shanghai"],
  "CVT": ["Atlantic/Cape_Verde"],
  "CXT": ["Indian/Christmas"],
  "DAVT": ["Antarctica/Davis"],
  "DDUT": ["Antarctica/DumontDUrville"],
  "EASST": ["Pacific/Easter"],
  "EAST": ["Pacific/Easter"],
  "EAT": ["Africa/Nairobi"],
  "ECT": ["America/Guayaquil"],
  "EDT": ["America/New_York", "America/Halifax"],
  "EEST": ["Asia/Nicosia", "Europe/Istanbul"],
  "EET": ["Asia/Nicosia", "Europe/Istanbul"],
  "EGST": ["America/Scoresbysund"],
  "EGT": ["America/Scoresbysund"],
  "EST": ["America/New_York", "America/Halifax", "Asia/Baghdad"],
  "FET": ["Europe/Minsk"],
  "FJT": ["Pacific/Fiji"],
  "FKST": ["Atlantic/Stanley"],
  "FKT": ["Atlantic/Stanley"],
  "FNT": ["America/Noronha"],
  "GALT": ["Pacific/Galapagos"],
  "GAMT": ["Pacific/Gambier"],
  "GET": ["Asia/Tbilisi"],
  "GFT": ["America/Cayenne"],
  "GILT": ["Pacific/Tarawa"],
  "GIT": ["Pacific/Tarawa"],
  "GMT": ["Etc/GMT"],
  "GST": ["Asia/Dubai", "Atlantic/South_Georgia"],
  "GYT": ["America/Guyana"],
  "HDT": ["Pacific/Honolulu"],
  "HAEC": ["Europe/Paris"],
  "HST": ["Pacific/Honolulu"],
  "HKT": ["Asia/Hong_Kong"],
  "HOVST": ["Asia/Hovd"],
  "HOVT": ["Asia/Hovd"],
  "ICT": ["Asia/Bangkok"],
  "IDT": ["Asia/Jerusalem"],
  "IOT": ["Indian/Chagos"],
  "IRDT": ["Asia/Tehran"],
  "IRKT": ["Asia/Irkutsk"],
  "IRST": ["Asia/Tehran"],
  "IST": ["Asia/Kolkata", "Asia/Colombo", "Asia/Jerusalem"],
  "JST": ["Asia/Tokyo"],
  "KALT": ["Asia/Kolkata"],
  "KGT": ["Asia/Bishkek"],
  "KOST": ["Pacific/Kosrae"],
  "KRAT": ["Asia/Krasnoyarsk"],
  "KST": ["Asia/Seoul"],
  "KUYT": ["Asia/Qyzylorda"],
  "LHST": ["Australia/Lord_Howe", "Pacific/Lord_Howe"],
  "LINT": ["Pacific/Kiritimati"],
  "MAGT": ["Asia/Magadan"],
  "MART": ["Pacific/Marquesas"],
  "MAWT": ["Antarctica/Mawson"],
  "MDT": ["America/Denver"],
  "MET": ["Europe/Paris"],
  "MEST": ["Europe/Paris"],
  "MHT": ["Pacific/Majuro"],
  "MIST": ["Antarctica/Macquarie"],
  "MIT": ["Pacific/Apia"],
  "MMT": ["Asia/Rangoon"],
  "MSK": ["Europe/Moscow"],
  "MST": ["America/Denver", "America/Phoenix", "Asia/Ulaanbaatar", "Asia/Ho_Chi_Minh"],
  "MUT": ["Indian/Mauritius"],
  "MVT": ["Indian/Maldives"],
  "MYT": ["Asia/Kuala_Lumpur"],
  "NCT": ["Pacific/Noumea"],
  "NDT": ["America/St_Johns"],
  "NFT": ["Pacific/Norfolk"],
  "NOVT": ["Asia/Novosibirsk"],
  "NPT": ["Asia/Kathmandu"],
  "NST": ["America/St_Johns"],
  "NT": ["America/St_Johns"],
  "NUT": ["Pacific/Niue"],
  "NZDT": ["Pacific/Auckland"],
  "NZST": ["Pacific/Auckland"],
  "OMSST": ["Asia/Omsk"],
  "OMST": ["Asia/Omsk"],
  "ORAT": ["Asia/Oral"],
  "PDT": ["America/Los_Angeles"],
  "PET": ["America/Lima"],
  "PETT": ["Asia/Kamchatka"],
  "PGT": ["Pacific/Port_Moresby"],
  "PHOT": ["Pacific/Enderbury"],
  "PHT": ["Asia/Manila"],
  "PKT": ["Asia/Karachi"],
  "PMDT": ["America/Miquelon"],
  "PMST": ["America/Miquelon"],
  "PONT": ["Pacific/Pohnpei"],
  "PST": ["America/Los_Angeles", "America/Tijuana", "Asia/Ulaanbaatar", "America/Ho_Chi_Minh"],
  "PT": ["America/Los_Angeles"],
  "PWT": ["Pacific/Palau"],
  "PYST": ["America/Asuncion"],
  "PYT": ["America/Asuncion"],
  "QYZT": ["Asia/Qyzylorda"],
  "RET": ["Indian/Reunion"],
  "ROTT": ["America/Port_of_Spain"],
  "SAKT": ["Asia/Sakhalin"],
  "SAMT": ["Europe/Samara"],
  "SAST": ["Africa/Johannesburg"],
  "SBT": ["Pacific/Guadalcanal"],
  "SCT": ["Indian/Mahe"],
  "SDT": ["America/Santo_Domingo"],
  "SGT": ["Asia/Singapore"],
  "SLST": ["Asia/Colombo"],
  "SRET": ["Asia/Srednekolymsk"],
  "SRT": ["America/Paramaribo"],
  "SST": ["Pacific/Apia", "Pacific/Pago_Pago"],
  "SYOT": ["Antarctica/Syowa"],
  "TAHT": ["Pacific/Tahiti"],
  "THA": ["Asia/Bangkok"],
  "TFT": ["Indian/Kerguelen"],
  "TJT": ["Asia/Dushanbe"],
  "TKT": ["Pacific/Fakaofo"],
  "TLT": ["Asia/Dili"],
  "TMT": ["Asia/Ashgabat"],
  "TOT": ["Pacific/Tongatapu"],
  "TVT": ["Pacific/Funafuti"],
  "ULAT": ["Asia/Ulaanbaatar"],
  "UTC": ["Etc/UTC"],
  "UYST": ["America/Montevideo"],
  "UYT": ["America/Montevideo"],
  "UZT": ["Asia/Tashkent"],
  "VET": ["America/Caracas"],
  "VLAST": ["Asia/Vladivostok"],
  "VLAT": ["Asia/Vladivostok"],
  "VOST": ["Antarctica/Vostok"],
  "VUT": ["Pacific/Efate"],
  "WAKT": ["Pacific/Wake"],
  "WAST": ["Africa/Windhoek"],
  "WAT": ["Africa/Lagos"],
  "WEST": ["Europe/Lisbon"],
  "WET": ["Europe/Lisbon"],
  "WFT": ["Pacific/Wallis"],
  "WGST": ["America/Godthab"],
  "WGT": ["America/Godthab"],
  "WIB": ["Asia/Jakarta"],
  "WIT": ["Asia/Jayapura"],
  "WITA": ["Asia/Makassar"],
  "WST": ["Pacific/Apia", "Pacific/Pago_Pago"],
  "YAKT": ["Asia/Yakutsk"],
  "YEKST": ["Asia/Yekaterinburg"],
  "YEKT": ["Asia/Yekaterinburg"]
};

export default timezones;